package com.employeemanagement.demo.model;

import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Model class for Privilege entity
 * 
 * @author 2144388
 *
 */
@Data
@Entity
@Schema(description = "Privilege Model Information")
public class Privilege {

	/**
	 * Unique auto-generated privilege ID
	 */
	@Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Autogenerated Privilege Id")
	@Id
	@Column(name = "privilege_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer privilegeId;

	/**
	 * Name of privilege
	 */
	@Schema(description = "Name of privilege")
	@Column(name = "privilege_name")
	private String privilegeName;

	/**
	 * Roles having the privilege
	 */
	@Schema(description = "Roles having the privilege")
	@JsonIgnore
	@ManyToMany(mappedBy = "privileges")
	private Collection<Role> roles;

}
